//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace _3G
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Database> Databases
        {
            get
            {
                if ((_Databases == null))
                {
                    _Databases = base.CreateObjectSet<Database>("Databases");
                }
                return _Databases;
            }
        }
        private ObjectSet<Database> _Databases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Masterlist> Masterlists
        {
            get
            {
                if ((_Masterlists == null))
                {
                    _Masterlists = base.CreateObjectSet<Masterlist>("Masterlists");
                }
                return _Masterlists;
            }
        }
        private ObjectSet<Masterlist> _Masterlists;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Databases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDatabases(Database database)
        {
            base.AddObject("Databases", database);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Masterlists EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMasterlists(Masterlist masterlist)
        {
            base.AddObject("Masterlists", masterlist);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Database")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Database : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Database object.
        /// </summary>
        /// <param name="s_N">Initial value of the S_N property.</param>
        /// <param name="full_Name">Initial value of the Full_Name property.</param>
        public static Database CreateDatabase(global::System.Decimal s_N, global::System.String full_Name)
        {
            Database database = new Database();
            database.S_N = s_N;
            database.Full_Name = full_Name;
            return database;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal S_N
        {
            get
            {
                return _S_N;
            }
            set
            {
                if (_S_N != value)
                {
                    OnS_NChanging(value);
                    ReportPropertyChanging("S_N");
                    _S_N = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("S_N");
                    OnS_NChanged();
                }
            }
        }
        private global::System.Decimal _S_N;
        partial void OnS_NChanging(global::System.Decimal value);
        partial void OnS_NChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Full_Name
        {
            get
            {
                return _Full_Name;
            }
            set
            {
                OnFull_NameChanging(value);
                ReportPropertyChanging("Full_Name");
                _Full_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Full_Name");
                OnFull_NameChanged();
            }
        }
        private global::System.String _Full_Name;
        partial void OnFull_NameChanging(global::System.String value);
        partial void OnFull_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date__MM_DD_YYYY_
        {
            get
            {
                return _Date__MM_DD_YYYY_;
            }
            set
            {
                OnDate__MM_DD_YYYY_Changing(value);
                ReportPropertyChanging("Date__MM_DD_YYYY_");
                _Date__MM_DD_YYYY_ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date__MM_DD_YYYY_");
                OnDate__MM_DD_YYYY_Changed();
            }
        }
        private Nullable<global::System.DateTime> _Date__MM_DD_YYYY_;
        partial void OnDate__MM_DD_YYYY_Changing(Nullable<global::System.DateTime> value);
        partial void OnDate__MM_DD_YYYY_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Day
        {
            get
            {
                return _Day;
            }
            set
            {
                OnDayChanging(value);
                ReportPropertyChanging("Day");
                _Day = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Day");
                OnDayChanged();
            }
        }
        private global::System.String _Day;
        partial void OnDayChanging(global::System.String value);
        partial void OnDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sub_Location__Platform_Only_
        {
            get
            {
                return _Sub_Location__Platform_Only_;
            }
            set
            {
                OnSub_Location__Platform_Only_Changing(value);
                ReportPropertyChanging("Sub_Location__Platform_Only_");
                _Sub_Location__Platform_Only_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sub_Location__Platform_Only_");
                OnSub_Location__Platform_Only_Changed();
            }
        }
        private global::System.String _Sub_Location__Platform_Only_;
        partial void OnSub_Location__Platform_Only_Changing(global::System.String value);
        partial void OnSub_Location__Platform_Only_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Requested_Shift_Timing__Start___08_00_00_AM_PM_Format_
        {
            get
            {
                return _Requested_Shift_Timing__Start___08_00_00_AM_PM_Format_;
            }
            set
            {
                OnRequested_Shift_Timing__Start___08_00_00_AM_PM_Format_Changing(value);
                ReportPropertyChanging("Requested_Shift_Timing__Start___08_00_00_AM_PM_Format_");
                _Requested_Shift_Timing__Start___08_00_00_AM_PM_Format_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Requested_Shift_Timing__Start___08_00_00_AM_PM_Format_");
                OnRequested_Shift_Timing__Start___08_00_00_AM_PM_Format_Changed();
            }
        }
        private global::System.String _Requested_Shift_Timing__Start___08_00_00_AM_PM_Format_;
        partial void OnRequested_Shift_Timing__Start___08_00_00_AM_PM_Format_Changing(global::System.String value);
        partial void OnRequested_Shift_Timing__Start___08_00_00_AM_PM_Format_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Requested_Shift_Timing__End____08_00_00_AM_PM_Format_
        {
            get
            {
                return _Requested_Shift_Timing__End____08_00_00_AM_PM_Format_;
            }
            set
            {
                OnRequested_Shift_Timing__End____08_00_00_AM_PM_Format_Changing(value);
                ReportPropertyChanging("Requested_Shift_Timing__End____08_00_00_AM_PM_Format_");
                _Requested_Shift_Timing__End____08_00_00_AM_PM_Format_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Requested_Shift_Timing__End____08_00_00_AM_PM_Format_");
                OnRequested_Shift_Timing__End____08_00_00_AM_PM_Format_Changed();
            }
        }
        private global::System.String _Requested_Shift_Timing__End____08_00_00_AM_PM_Format_;
        partial void OnRequested_Shift_Timing__End____08_00_00_AM_PM_Format_Changing(global::System.String value);
        partial void OnRequested_Shift_Timing__End____08_00_00_AM_PM_Format_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Break_
        {
            get
            {
                return _Break_;
            }
            set
            {
                OnBreak_Changing(value);
                ReportPropertyChanging("Break_");
                _Break_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Break_");
                OnBreak_Changed();
            }
        }
        private global::System.String _Break_;
        partial void OnBreak_Changing(global::System.String value);
        partial void OnBreak_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Overtime____OT_
        {
            get
            {
                return _Overtime____OT_;
            }
            set
            {
                OnOvertime____OT_Changing(value);
                ReportPropertyChanging("Overtime____OT_");
                _Overtime____OT_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Overtime____OT_");
                OnOvertime____OT_Changed();
            }
        }
        private global::System.String _Overtime____OT_;
        partial void OnOvertime____OT_Changing(global::System.String value);
        partial void OnOvertime____OT_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Start_Time___08_00_00_AM_PM_Format_
        {
            get
            {
                return _Start_Time___08_00_00_AM_PM_Format_;
            }
            set
            {
                OnStart_Time___08_00_00_AM_PM_Format_Changing(value);
                ReportPropertyChanging("Start_Time___08_00_00_AM_PM_Format_");
                _Start_Time___08_00_00_AM_PM_Format_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Start_Time___08_00_00_AM_PM_Format_");
                OnStart_Time___08_00_00_AM_PM_Format_Changed();
            }
        }
        private global::System.String _Start_Time___08_00_00_AM_PM_Format_;
        partial void OnStart_Time___08_00_00_AM_PM_Format_Changing(global::System.String value);
        partial void OnStart_Time___08_00_00_AM_PM_Format_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String End_Time___08_00_00_AM_PM_Format_
        {
            get
            {
                return _End_Time___08_00_00_AM_PM_Format_;
            }
            set
            {
                OnEnd_Time___08_00_00_AM_PM_Format_Changing(value);
                ReportPropertyChanging("End_Time___08_00_00_AM_PM_Format_");
                _End_Time___08_00_00_AM_PM_Format_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("End_Time___08_00_00_AM_PM_Format_");
                OnEnd_Time___08_00_00_AM_PM_Format_Changed();
            }
        }
        private global::System.String _End_Time___08_00_00_AM_PM_Format_;
        partial void OnEnd_Time___08_00_00_AM_PM_Format_Changing(global::System.String value);
        partial void OnEnd_Time___08_00_00_AM_PM_Format_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No__of_Requested_Headcount
        {
            get
            {
                return _No__of_Requested_Headcount;
            }
            set
            {
                OnNo__of_Requested_HeadcountChanging(value);
                ReportPropertyChanging("No__of_Requested_Headcount");
                _No__of_Requested_Headcount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No__of_Requested_Headcount");
                OnNo__of_Requested_HeadcountChanged();
            }
        }
        private global::System.String _No__of_Requested_Headcount;
        partial void OnNo__of_Requested_HeadcountChanging(global::System.String value);
        partial void OnNo__of_Requested_HeadcountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No__of_Actual_Headcount
        {
            get
            {
                return _No__of_Actual_Headcount;
            }
            set
            {
                OnNo__of_Actual_HeadcountChanging(value);
                ReportPropertyChanging("No__of_Actual_Headcount");
                _No__of_Actual_Headcount = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No__of_Actual_Headcount");
                OnNo__of_Actual_HeadcountChanged();
            }
        }
        private global::System.String _No__of_Actual_Headcount;
        partial void OnNo__of_Actual_HeadcountChanging(global::System.String value);
        partial void OnNo__of_Actual_HeadcountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No__of_Requested_Hours
        {
            get
            {
                return _No__of_Requested_Hours;
            }
            set
            {
                OnNo__of_Requested_HoursChanging(value);
                ReportPropertyChanging("No__of_Requested_Hours");
                _No__of_Requested_Hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No__of_Requested_Hours");
                OnNo__of_Requested_HoursChanged();
            }
        }
        private global::System.String _No__of_Requested_Hours;
        partial void OnNo__of_Requested_HoursChanging(global::System.String value);
        partial void OnNo__of_Requested_HoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Shortage_of_Requested_Hours
        {
            get
            {
                return _Shortage_of_Requested_Hours;
            }
            set
            {
                OnShortage_of_Requested_HoursChanging(value);
                ReportPropertyChanging("Shortage_of_Requested_Hours");
                _Shortage_of_Requested_Hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Shortage_of_Requested_Hours");
                OnShortage_of_Requested_HoursChanged();
            }
        }
        private global::System.String _Shortage_of_Requested_Hours;
        partial void OnShortage_of_Requested_HoursChanging(global::System.String value);
        partial void OnShortage_of_Requested_HoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reason_for_The_Shortage_of_Hours
        {
            get
            {
                return _Reason_for_The_Shortage_of_Hours;
            }
            set
            {
                OnReason_for_The_Shortage_of_HoursChanging(value);
                ReportPropertyChanging("Reason_for_The_Shortage_of_Hours");
                _Reason_for_The_Shortage_of_Hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Reason_for_The_Shortage_of_Hours");
                OnReason_for_The_Shortage_of_HoursChanged();
            }
        }
        private global::System.String _Reason_for_The_Shortage_of_Hours;
        partial void OnReason_for_The_Shortage_of_HoursChanging(global::System.String value);
        partial void OnReason_for_The_Shortage_of_HoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Total_No__of_Hours_Fulfilled
        {
            get
            {
                return _Total_No__of_Hours_Fulfilled;
            }
            set
            {
                OnTotal_No__of_Hours_FulfilledChanging(value);
                ReportPropertyChanging("Total_No__of_Hours_Fulfilled");
                _Total_No__of_Hours_Fulfilled = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Total_No__of_Hours_Fulfilled");
                OnTotal_No__of_Hours_FulfilledChanged();
            }
        }
        private global::System.String _Total_No__of_Hours_Fulfilled;
        partial void OnTotal_No__of_Hours_FulfilledChanging(global::System.String value);
        partial void OnTotal_No__of_Hours_FulfilledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Total_No__of_Manhours
        {
            get
            {
                return _Total_No__of_Manhours;
            }
            set
            {
                OnTotal_No__of_ManhoursChanging(value);
                ReportPropertyChanging("Total_No__of_Manhours");
                _Total_No__of_Manhours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Total_No__of_Manhours");
                OnTotal_No__of_ManhoursChanged();
            }
        }
        private global::System.String _Total_No__of_Manhours;
        partial void OnTotal_No__of_ManhoursChanging(global::System.String value);
        partial void OnTotal_No__of_ManhoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Is_This_ORT____OJT___Spare___Non_Activated_Standby_
        {
            get
            {
                return _Is_This_ORT____OJT___Spare___Non_Activated_Standby_;
            }
            set
            {
                OnIs_This_ORT____OJT___Spare___Non_Activated_Standby_Changing(value);
                ReportPropertyChanging("Is_This_ORT____OJT___Spare___Non_Activated_Standby_");
                _Is_This_ORT____OJT___Spare___Non_Activated_Standby_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Is_This_ORT____OJT___Spare___Non_Activated_Standby_");
                OnIs_This_ORT____OJT___Spare___Non_Activated_Standby_Changed();
            }
        }
        private global::System.String _Is_This_ORT____OJT___Spare___Non_Activated_Standby_;
        partial void OnIs_This_ORT____OJT___Spare___Non_Activated_Standby_Changing(global::System.String value);
        partial void OnIs_This_ORT____OJT___Spare___Non_Activated_Standby_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No__of_ORT___OJT___Spare___Non_Activated_Standby
        {
            get
            {
                return _No__of_ORT___OJT___Spare___Non_Activated_Standby;
            }
            set
            {
                OnNo__of_ORT___OJT___Spare___Non_Activated_StandbyChanging(value);
                ReportPropertyChanging("No__of_ORT___OJT___Spare___Non_Activated_Standby");
                _No__of_ORT___OJT___Spare___Non_Activated_Standby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No__of_ORT___OJT___Spare___Non_Activated_Standby");
                OnNo__of_ORT___OJT___Spare___Non_Activated_StandbyChanged();
            }
        }
        private global::System.String _No__of_ORT___OJT___Spare___Non_Activated_Standby;
        partial void OnNo__of_ORT___OJT___Spare___Non_Activated_StandbyChanging(global::System.String value);
        partial void OnNo__of_ORT___OJT___Spare___Non_Activated_StandbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Total_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_Standby
        {
            get
            {
                return _Total_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_Standby;
            }
            set
            {
                OnTotal_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_StandbyChanging(value);
                ReportPropertyChanging("Total_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_Standby");
                _Total_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_Standby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Total_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_Standby");
                OnTotal_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_StandbyChanged();
            }
        }
        private global::System.String _Total_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_Standby;
        partial void OnTotal_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_StandbyChanging(global::System.String value);
        partial void OnTotal_No__of_Hours_for_ORT___OJT___Spare___Non_Activated_StandbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Classification_of_Payment
        {
            get
            {
                return _Classification_of_Payment;
            }
            set
            {
                OnClassification_of_PaymentChanging(value);
                ReportPropertyChanging("Classification_of_Payment");
                _Classification_of_Payment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Classification_of_Payment");
                OnClassification_of_PaymentChanged();
            }
        }
        private global::System.String _Classification_of_Payment;
        partial void OnClassification_of_PaymentChanging(global::System.String value);
        partial void OnClassification_of_PaymentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hourly___Daily_Pay_Type
        {
            get
            {
                return _Hourly___Daily_Pay_Type;
            }
            set
            {
                OnHourly___Daily_Pay_TypeChanging(value);
                ReportPropertyChanging("Hourly___Daily_Pay_Type");
                _Hourly___Daily_Pay_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hourly___Daily_Pay_Type");
                OnHourly___Daily_Pay_TypeChanged();
            }
        }
        private global::System.String _Hourly___Daily_Pay_Type;
        partial void OnHourly___Daily_Pay_TypeChanging(global::System.String value);
        partial void OnHourly___Daily_Pay_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Salary_Rate__Variable_
        {
            get
            {
                return _Salary_Rate__Variable_;
            }
            set
            {
                OnSalary_Rate__Variable_Changing(value);
                ReportPropertyChanging("Salary_Rate__Variable_");
                _Salary_Rate__Variable_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Salary_Rate__Variable_");
                OnSalary_Rate__Variable_Changed();
            }
        }
        private global::System.String _Salary_Rate__Variable_;
        partial void OnSalary_Rate__Variable_Changing(global::System.String value);
        partial void OnSalary_Rate__Variable_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String No__of_5_Mins_Block_of_Lateness__Non_Excusable_
        {
            get
            {
                return _No__of_5_Mins_Block_of_Lateness__Non_Excusable_;
            }
            set
            {
                OnNo__of_5_Mins_Block_of_Lateness__Non_Excusable_Changing(value);
                ReportPropertyChanging("No__of_5_Mins_Block_of_Lateness__Non_Excusable_");
                _No__of_5_Mins_Block_of_Lateness__Non_Excusable_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("No__of_5_Mins_Block_of_Lateness__Non_Excusable_");
                OnNo__of_5_Mins_Block_of_Lateness__Non_Excusable_Changed();
            }
        }
        private global::System.String _No__of_5_Mins_Block_of_Lateness__Non_Excusable_;
        partial void OnNo__of_5_Mins_Block_of_Lateness__Non_Excusable_Changing(global::System.String value);
        partial void OnNo__of_5_Mins_Block_of_Lateness__Non_Excusable_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Salary_Deduction_for_Lateness
        {
            get
            {
                return _Salary_Deduction_for_Lateness;
            }
            set
            {
                OnSalary_Deduction_for_LatenessChanging(value);
                ReportPropertyChanging("Salary_Deduction_for_Lateness");
                _Salary_Deduction_for_Lateness = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Salary_Deduction_for_Lateness");
                OnSalary_Deduction_for_LatenessChanged();
            }
        }
        private global::System.String _Salary_Deduction_for_Lateness;
        partial void OnSalary_Deduction_for_LatenessChanging(global::System.String value);
        partial void OnSalary_Deduction_for_LatenessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Salary_Deduction_For_Absence
        {
            get
            {
                return _Salary_Deduction_For_Absence;
            }
            set
            {
                OnSalary_Deduction_For_AbsenceChanging(value);
                ReportPropertyChanging("Salary_Deduction_For_Absence");
                _Salary_Deduction_For_Absence = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Salary_Deduction_For_Absence");
                OnSalary_Deduction_For_AbsenceChanged();
            }
        }
        private global::System.String _Salary_Deduction_For_Absence;
        partial void OnSalary_Deduction_For_AbsenceChanging(global::System.String value);
        partial void OnSalary_Deduction_For_AbsenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Activated_
        {
            get
            {
                return _Activated_;
            }
            set
            {
                OnActivated_Changing(value);
                ReportPropertyChanging("Activated_");
                _Activated_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Activated_");
                OnActivated_Changed();
            }
        }
        private global::System.String _Activated_;
        partial void OnActivated_Changing(global::System.String value);
        partial void OnActivated_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Activation_Hours
        {
            get
            {
                return _Activation_Hours;
            }
            set
            {
                OnActivation_HoursChanging(value);
                ReportPropertyChanging("Activation_Hours");
                _Activation_Hours = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Activation_Hours");
                OnActivation_HoursChanged();
            }
        }
        private global::System.String _Activation_Hours;
        partial void OnActivation_HoursChanging(global::System.String value);
        partial void OnActivation_HoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Activation_Allowance_Rate
        {
            get
            {
                return _Activation_Allowance_Rate;
            }
            set
            {
                OnActivation_Allowance_RateChanging(value);
                ReportPropertyChanging("Activation_Allowance_Rate");
                _Activation_Allowance_Rate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Activation_Allowance_Rate");
                OnActivation_Allowance_RateChanged();
            }
        }
        private global::System.String _Activation_Allowance_Rate;
        partial void OnActivation_Allowance_RateChanging(global::System.String value);
        partial void OnActivation_Allowance_RateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Total_Salary
        {
            get
            {
                return _Total_Salary;
            }
            set
            {
                OnTotal_SalaryChanging(value);
                ReportPropertyChanging("Total_Salary");
                _Total_Salary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Total_Salary");
                OnTotal_SalaryChanged();
            }
        }
        private global::System.String _Total_Salary;
        partial void OnTotal_SalaryChanging(global::System.String value);
        partial void OnTotal_SalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Team_Leader_Additional_Hour
        {
            get
            {
                return _Team_Leader_Additional_Hour;
            }
            set
            {
                OnTeam_Leader_Additional_HourChanging(value);
                ReportPropertyChanging("Team_Leader_Additional_Hour");
                _Team_Leader_Additional_Hour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Team_Leader_Additional_Hour");
                OnTeam_Leader_Additional_HourChanged();
            }
        }
        private global::System.String _Team_Leader_Additional_Hour;
        partial void OnTeam_Leader_Additional_HourChanging(global::System.String value);
        partial void OnTeam_Leader_Additional_HourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Team_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_
        {
            get
            {
                return _Team_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_;
            }
            set
            {
                OnTeam_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_Changing(value);
                ReportPropertyChanging("Team_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_");
                _Team_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Team_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_");
                OnTeam_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_Changed();
            }
        }
        private global::System.String _Team_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_;
        partial void OnTeam_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_Changing(global::System.String value);
        partial void OnTeam_Leader_Additional_Salary___Additional_Hr_x_Salary_Rate_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DAA___2_
        {
            get
            {
                return _DAA___2_;
            }
            set
            {
                OnDAA___2_Changing(value);
                ReportPropertyChanging("DAA___2_");
                _DAA___2_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DAA___2_");
                OnDAA___2_Changed();
            }
        }
        private global::System.String _DAA___2_;
        partial void OnDAA___2_Changing(global::System.String value);
        partial void OnDAA___2_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Uniform_Return_____10__Purchases______10___ve_
        {
            get
            {
                return _Uniform_Return_____10__Purchases______10___ve_;
            }
            set
            {
                OnUniform_Return_____10__Purchases______10___ve_Changing(value);
                ReportPropertyChanging("Uniform_Return_____10__Purchases______10___ve_");
                _Uniform_Return_____10__Purchases______10___ve_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Uniform_Return_____10__Purchases______10___ve_");
                OnUniform_Return_____10__Purchases______10___ve_Changed();
            }
        }
        private global::System.String _Uniform_Return_____10__Purchases______10___ve_;
        partial void OnUniform_Return_____10__Purchases______10___ve_Changing(global::System.String value);
        partial void OnUniform_Return_____10__Purchases______10___ve_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Back_Support__Return____20_Purchase______20___ve_
        {
            get
            {
                return _Back_Support__Return____20_Purchase______20___ve_;
            }
            set
            {
                OnBack_Support__Return____20_Purchase______20___ve_Changing(value);
                ReportPropertyChanging("Back_Support__Return____20_Purchase______20___ve_");
                _Back_Support__Return____20_Purchase______20___ve_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Back_Support__Return____20_Purchase______20___ve_");
                OnBack_Support__Return____20_Purchase______20___ve_Changed();
            }
        }
        private global::System.String _Back_Support__Return____20_Purchase______20___ve_;
        partial void OnBack_Support__Return____20_Purchase______20___ve_Changing(global::System.String value);
        partial void OnBack_Support__Return____20_Purchase______20___ve_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Miscellaneous__Adjustment_Reimbursement_
        {
            get
            {
                return _Miscellaneous__Adjustment_Reimbursement_;
            }
            set
            {
                OnMiscellaneous__Adjustment_Reimbursement_Changing(value);
                ReportPropertyChanging("Miscellaneous__Adjustment_Reimbursement_");
                _Miscellaneous__Adjustment_Reimbursement_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Miscellaneous__Adjustment_Reimbursement_");
                OnMiscellaneous__Adjustment_Reimbursement_Changed();
            }
        }
        private global::System.String _Miscellaneous__Adjustment_Reimbursement_;
        partial void OnMiscellaneous__Adjustment_Reimbursement_Changing(global::System.String value);
        partial void OnMiscellaneous__Adjustment_Reimbursement_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Total_Salary__incl__Miscellaneous_Cost_
        {
            get
            {
                return _Total_Salary__incl__Miscellaneous_Cost_;
            }
            set
            {
                OnTotal_Salary__incl__Miscellaneous_Cost_Changing(value);
                ReportPropertyChanging("Total_Salary__incl__Miscellaneous_Cost_");
                _Total_Salary__incl__Miscellaneous_Cost_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Total_Salary__incl__Miscellaneous_Cost_");
                OnTotal_Salary__incl__Miscellaneous_Cost_Changed();
            }
        }
        private global::System.String _Total_Salary__incl__Miscellaneous_Cost_;
        partial void OnTotal_Salary__incl__Miscellaneous_Cost_Changing(global::System.String value);
        partial void OnTotal_Salary__incl__Miscellaneous_Cost_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hourly___Daily_Invoice_Type
        {
            get
            {
                return _Hourly___Daily_Invoice_Type;
            }
            set
            {
                OnHourly___Daily_Invoice_TypeChanging(value);
                ReportPropertyChanging("Hourly___Daily_Invoice_Type");
                _Hourly___Daily_Invoice_Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hourly___Daily_Invoice_Type");
                OnHourly___Daily_Invoice_TypeChanged();
            }
        }
        private global::System.String _Hourly___Daily_Invoice_Type;
        partial void OnHourly___Daily_Invoice_TypeChanging(global::System.String value);
        partial void OnHourly___Daily_Invoice_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Invoice_Rate
        {
            get
            {
                return _Invoice_Rate;
            }
            set
            {
                OnInvoice_RateChanging(value);
                ReportPropertyChanging("Invoice_Rate");
                _Invoice_Rate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Invoice_Rate");
                OnInvoice_RateChanged();
            }
        }
        private global::System.String _Invoice_Rate;
        partial void OnInvoice_RateChanging(global::System.String value);
        partial void OnInvoice_RateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Total_Revenue__Invoice_
        {
            get
            {
                return _Total_Revenue__Invoice_;
            }
            set
            {
                OnTotal_Revenue__Invoice_Changing(value);
                ReportPropertyChanging("Total_Revenue__Invoice_");
                _Total_Revenue__Invoice_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Total_Revenue__Invoice_");
                OnTotal_Revenue__Invoice_Changed();
            }
        }
        private global::System.String _Total_Revenue__Invoice_;
        partial void OnTotal_Revenue__Invoice_Changing(global::System.String value);
        partial void OnTotal_Revenue__Invoice_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Negative_Revenue__Opportunity_Lost_
        {
            get
            {
                return _Negative_Revenue__Opportunity_Lost_;
            }
            set
            {
                OnNegative_Revenue__Opportunity_Lost_Changing(value);
                ReportPropertyChanging("Negative_Revenue__Opportunity_Lost_");
                _Negative_Revenue__Opportunity_Lost_ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Negative_Revenue__Opportunity_Lost_");
                OnNegative_Revenue__Opportunity_Lost_Changed();
            }
        }
        private global::System.String _Negative_Revenue__Opportunity_Lost_;
        partial void OnNegative_Revenue__Opportunity_Lost_Changing(global::System.String value);
        partial void OnNegative_Revenue__Opportunity_Lost_Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OPS_Additional_Cost
        {
            get
            {
                return _OPS_Additional_Cost;
            }
            set
            {
                OnOPS_Additional_CostChanging(value);
                ReportPropertyChanging("OPS_Additional_Cost");
                _OPS_Additional_Cost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OPS_Additional_Cost");
                OnOPS_Additional_CostChanged();
            }
        }
        private global::System.String _OPS_Additional_Cost;
        partial void OnOPS_Additional_CostChanging(global::System.String value);
        partial void OnOPS_Additional_CostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gross_Profit____
        {
            get
            {
                return _Gross_Profit____;
            }
            set
            {
                OnGross_Profit____Changing(value);
                ReportPropertyChanging("Gross_Profit____");
                _Gross_Profit____ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gross_Profit____");
                OnGross_Profit____Changed();
            }
        }
        private global::System.String _Gross_Profit____;
        partial void OnGross_Profit____Changing(global::System.String value);
        partial void OnGross_Profit____Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CASH_PAYMENT
        {
            get
            {
                return _CASH_PAYMENT;
            }
            set
            {
                OnCASH_PAYMENTChanging(value);
                ReportPropertyChanging("CASH_PAYMENT");
                _CASH_PAYMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CASH_PAYMENT");
                OnCASH_PAYMENTChanged();
            }
        }
        private global::System.String _CASH_PAYMENT;
        partial void OnCASH_PAYMENTChanging(global::System.String value);
        partial void OnCASH_PAYMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type_of_Worker
        {
            get
            {
                return _Type_of_Worker;
            }
            set
            {
                OnType_of_WorkerChanging(value);
                ReportPropertyChanging("Type_of_Worker");
                _Type_of_Worker = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type_of_Worker");
                OnType_of_WorkerChanged();
            }
        }
        private global::System.String _Type_of_Worker;
        partial void OnType_of_WorkerChanging(global::System.String value);
        partial void OnType_of_WorkerChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Masterlist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Masterlist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Masterlist object.
        /// </summary>
        /// <param name="full_Name">Initial value of the Full_Name property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        public static Masterlist CreateMasterlist(global::System.String full_Name, global::System.DateTime date, global::System.TimeSpan time)
        {
            Masterlist masterlist = new Masterlist();
            masterlist.Full_Name = full_Name;
            masterlist.Date = date;
            masterlist.Time = time;
            return masterlist;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Full_Name
        {
            get
            {
                return _Full_Name;
            }
            set
            {
                if (_Full_Name != value)
                {
                    OnFull_NameChanging(value);
                    ReportPropertyChanging("Full_Name");
                    _Full_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Full_Name");
                    OnFull_NameChanged();
                }
            }
        }
        private global::System.String _Full_Name;
        partial void OnFull_NameChanging(global::System.String value);
        partial void OnFull_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.TimeSpan _Time;
        partial void OnTimeChanging(global::System.TimeSpan value);
        partial void OnTimeChanged();

        #endregion

    
    }

    #endregion

    
}
